name: Codecov test en npm install
on: 
  push:
    branches:
    - main
jobs:
  npm_install:
    name: getting the OS
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout 
        uses: actions/checkout@v4
        
      - name: setup npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: npm dependencies     
        run: npm ci
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  
  
